# Generated by Django 4.1.7 on 2023-06-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroatividades',
            name='Equipamento',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='inspecao_equipamentos',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='observacao_inspecao',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='ronda',
        ),
        migrations.AlterField(
            model_name='registroatividades',
            name='data_registro',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='InspecaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspecao', models.TextField()),
                ('observacao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.equipamento')),
                ('registro_atividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.registroatividades')),
            ],
        ),
        migrations.AddField(
            model_name='registroatividades',
            name='equipamentos',
            field=models.ManyToManyField(through='registro.InspecaoEquipamento', to='registro.equipamento'),
        ),
    ]
