# Generated by Django 4.1.7 on 2023-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_registroatividades_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecaoequipamento',
            name='registro_atividades',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='equipamentos',
        ),
        migrations.AddField(
            model_name='registroatividades',
            name='inspecoes_equipamentos',
            field=models.ManyToManyField(to='registro.inspecaoequipamento'),
        ),
    ]
