# Generated by Django 4.1.7 on 2023-06-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_inspecaoequipamento_data_inspecao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicial_evento', models.DateTimeField()),
                ('hora_final_evento', models.DateTimeField()),
                ('ronda_interna', models.BooleanField()),
                ('ronda_externa', models.BooleanField()),
                ('visitas', models.TextField()),
                ('manobras', models.TextField()),
                ('imagens_videos', models.FileField(upload_to='registro/uploads/%Y-%m-%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='hora_final_evento',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='hora_inicial_evento',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='imagens_videos',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='manobras',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='ronda_externa',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='ronda_interna',
        ),
        migrations.RemoveField(
            model_name='registroatividades',
            name='visitas',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inspecaoequipamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroatividades',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='registroatividades',
            name='evento',
            field=models.ManyToManyField(to='registro.registroeventos'),
        ),
    ]
