# Generated by Django 4.1.7 on 2023-06-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_registroeventos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAtividades',
            new_name='RegistroAtividade',
        ),
        migrations.RenameModel(
            old_name='RegistroEventos',
            new_name='RegistroEvento',
        ),
    ]
