# Generated by Django 4.1.7 on 2023-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_rename_registroatividades_registroatividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividade',
            name='demanda',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='texto_demanda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
